[package]
name = "cloudsearch-node"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
cloudsearch-api = { path = "../cloudsearch-api" }
cloudsearch-common = { path = "../cloudsearch-common" }
cloudsearch-index = { path = "../cloudsearch-index" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[dev-dependencies]
libc = "0.2"
reqwest.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
