[package]
name = "cloudsearch-index"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
cloudsearch-common = { path = "../cloudsearch-common" }
cloudsearch-storage = { path = "../cloudsearch-storage" }
crc32c.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
rayon = { workspace = true }
memmap2.workspace = true

[dev-dependencies]
tempfile.workspace = true
criterion.workspace = true

[[bench]]
name = "search"
harness = false
